"""Reports and verifiable-evidence page."""

from html import escape

import streamlit as st

from sodif.reporting import FlightExports
from sodif.ui.pages.shared import render_flight_summary, render_page_intro
from sodif.ui.presentation import present_flight
from sodif.ui.state import current_exports, current_report


def render_evidence_hub(control_page: str) -> None:
    """Render the evidence package generated by the current demonstration."""
    render_page_intro(
        "Trasabilitate",
        "Rapoarte și dovezi",
        "Preia rezultatul demonstrației în formate pentru evaluare umană, audit automat "
        "și verificarea integrității.",
    )
    report = current_report()
    if report is None:
        _render_empty_state(control_page)
        return

    render_flight_summary(present_flight(report))
    exports = current_exports(report)
    _render_report_identity(report.report_id, report.completed_at.isoformat())
    _render_export_panel(exports)
    _render_package_contents()


def _render_empty_state(control_page: str) -> None:
    st.markdown(
        """
        <section class="sodif-empty-panel">
            <div class="sodif-ready-mark" aria-hidden="true"><span></span></div>
            <div><h2>Nu există încă un raport</h2>
            <p>Rulează demonstrația pentru a genera raportul Word, dovezile structurate,
            jurnalul de audit și manifestul de integritate.</p></div>
        </section>
        """,
        unsafe_allow_html=True,
    )
    with st.container(key="empty_control_link"):
        st.page_link(
            control_page,
            label="Deschide centrul de control",
            icon=":material/play_arrow:",
            use_container_width=False,
        )


def _render_report_identity(report_id: str, completed_at: str) -> None:
    sealed_at = escape(completed_at.replace("+00:00", "Z"))
    st.markdown(
        f"""
        <section class="sodif-report-identity">
            <div><small>Raport curent</small><code>{escape(report_id)}</code></div>
            <div><small>Generat la</small><strong>{sealed_at}</strong></div>
            <div><small>Integritate</small><strong>Verificabilă SHA-256</strong></div>
        </section>
        """,
        unsafe_allow_html=True,
    )


def _render_export_panel(exports: FlightExports) -> None:
    digest = f"{exports.bundle.digest[:25]}…{exports.bundle.digest[-10:]}"
    st.markdown(
        f"""
        <section class="sodif-export-panel">
            <div><div class="sodif-card-caption">Pachet de dovezi</div>
            <h2>Fișiere pregătite pentru preluare</h2>
            <p>Raport pentru analiză umană, date structurate, jurnal de audit și manifest
            de integritate, reunite într-un singur pachet verificabil.</p></div>
            <div class="sodif-bundle-digest"><small>Amprenta pachetului</small>
            <code>{escape(digest)}</code></div>
        </section>
        """,
        unsafe_allow_html=True,
    )
    bundle, document, structured, audit = st.columns(4)
    with bundle:
        st.download_button(
            "Pachet complet",
            data=exports.bundle.data,
            file_name=exports.bundle.filename,
            mime=exports.bundle.media_type,
            type="primary",
            icon=":material/archive:",
            use_container_width=True,
        )
    with document:
        st.download_button(
            "Raport Word",
            data=exports.document.data,
            file_name=exports.document.filename,
            mime=exports.document.media_type,
            icon=":material/description:",
            use_container_width=True,
        )
    with structured:
        st.download_button(
            "Date JSON",
            data=exports.report.data,
            file_name=exports.report.filename,
            mime=exports.report.media_type,
            icon=":material/data_object:",
            use_container_width=True,
        )
    with audit:
        st.download_button(
            "Jurnal de audit",
            data=exports.audit_log.data,
            file_name=exports.audit_log.filename,
            mime=exports.audit_log.media_type,
            icon=":material/receipt_long:",
            use_container_width=True,
        )


def _render_package_contents() -> None:
    st.markdown(
        '<div class="sodif-section-label">Conținutul pachetului</div>',
        unsafe_allow_html=True,
    )
    items = (
        ("description", "Raport pentru evaluare", "Verdicte, motive, efecte API și dovezi."),
        ("data_object", "Date structurate", "Rezultatul complet, pregătit pentru procesare."),
        (
            "receipt_long",
            "Jurnal de audit",
            "Evenimente ordonate și sigilate pentru trasabilitate.",
        ),
        (
            "verified",
            "Manifest de integritate",
            "Dimensiuni și amprente pentru verificarea fișierelor.",
        ),
    )
    columns = st.columns(4)
    for column, (icon, title, body) in zip(columns, items, strict=True):
        with column, st.container(border=True, key=f"evidence_item_{icon}"):
            st.markdown(f"#### :material/{icon}: {title}")
            st.caption(body)
