[theme]
primaryColor = "#0B8793"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6FA"
textColor = "#10233F"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

